# Generated by Django 3.2.8 on 2023-01-27 04:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('VideoLink', models.TextField(unique=True)),
                ('duration', models.CharField(max_length=200)),
                ('thumb', models.TextField(unique=True)),
                ('embed_code', models.TextField(unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('quality', models.CharField(max_length=30)),
            ],
        ),
    ]
